dist: trusty
sudo: false

language: node_js
node_js:
  - "9.5.0"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"
branches:
  only:
    - master

jobs:
  include:
    - stage: test
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d
    - script: yarn hk652f13d

stages:
  - test
